# Generated by Django 5.0.1 on 2024-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phonnumber',
        ),
        migrations.AddField(
            model_name='staff',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
