# Generated by Django 5.0.1 on 2024-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0003_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
