# Generated by Django 5.0.1 on 2024-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0004_cust_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
