# Generated by Django 5.0.1 on 2024-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0006_remove_cust_approved_remove_staff_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
