# Generated by Django 5.0.1 on 2024-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0007_staff_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=200)),
                ('bed_space', models.CharField(max_length=200)),
                ('room_id', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
