# Generated by Django 5.0.1 on 2024-02-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0008_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='img',
            new_name='data',
        ),
    ]
