# Generated by Django 5.0.1 on 2024-02-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotalapp', '0009_rename_img_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='bed_space',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
